### ISSUE TITLE
BPM off companion.   

### ISSUE THREAD

**Issue by Steffielight** [bitfocus/companion-module-thelightingcontroller#15] opened 2024-03-30 14:58 UTC
### Is this a feature relevant to companion itself, and not a module?

- [ ] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the feature

BPM off companion.   For quick dmx is it not possible to use music. Now the bpm from companion give the main bpm. Please make it possible to turn off. 

How i connect a light button from quick dmx to companion?

**Comment by bryce-seifert** [comment] 2024-04-13 23:37
I'm not sure I understand the request. Can you elaborate on what module you are using, and what your request is?

**Comment by Steffielight** [comment] 2024-04-14 09:39
Hi @bryce-seifert ,

I have A problem with the lightingcontroller quick dmx and companion. I try a lot of hours but i cant get off the BPM signal from companion off.

Some people talk about BPMcounter file and edit a line out to turn off BPM, but I have not a BPM counter file. I see only index.js.

Now companion send standard a BPM signal to the lightingcontroller software. I use BPM signal from other software. Now I would like to turn it off. How I can turn off from companion? It is a amazing software but I cant turn off the BPM.

Please help! Will be nice!

![Schermafbeelding 2024-04-13 112732](https://github.com/bitfocus/companion-module-chamsys-quickq/assets/165475805/186d9da4-21af-445f-a9e7-92ceadb72f09)

**Comment by bryce-seifert** [comment] 2024-04-14 15:22
Gotcha. Sorry, for the confusion–this is not the right repo for this module, not sure why it got transferred here. Going to transfer it to the right module now and hopefully they can assist.

**Comment by thargy** [comment] 2024-04-14 16:20
Closed as duplicate of #6.

**Closed as completed by thargy** 2024-04-14 16:20 UTC
Labels: duplicate
